name: precious
description: "Precious Present Truth Audio Book App."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+4

environment:
  sdk: ^3.6.0-263.0.dev

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Core Utilities
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  intl: ^0.20.1

  # HTTP - Using newer version with workaround
  http: ^1.2.2
  dio: ^5.7.0

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  #cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Web & Content
  webview_flutter: 3.0.4
  flutter_pdfview: ^1.3.4
  url_launcher: ^6.3.1
  share_plus: ^10.1.2

  # YouTube
  youtube_player_iframe: ^2.2.2
  youtube_explode_dart: ^2.3.9

  # Audio (updated to work with http 1.x)
  just_audio: ^0.9.34 # Primary audio player
  audioplayers: ^4.1.0 # iOS 12 compatible version
  audio_service: ^0.18.17
  audio_session: ^0.1.25

  # Video
  video_player: ^2.4.7
  chewie: ^1.3.4

  # System Features
  permission_handler: ^12.0.0+1
  flutter_downloader: ^1.11.6
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0 # Now compatible with http 1.x

  # Dev Tools
  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  # Allow timezone to work with http 1.x
  http: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
